### PR TITLE
Updated node version

### LINKED ISSUE #270: Node.js 12 actions are deprecated.
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16

### PR DESCRIPTION
**Pull request by saniales**
Fixes #270

### CODE REVIEW

**Review by akhilerm — APPROVED** [review]

**Comment by akhilerm** [comment]
@saniales Can you help with testing the action from `@main`. Updated the build with node16 updates

**Comment by saniales** [comment]
Yes I can what do you need?

**Comment by akhilerm** [comment]
If you are using this action, I guess it must be at `v2.0.0`. Can you test with `@main`? I have few test cases running with `@main`, and they are all green, but want to be sure before releasing `v2.1.0` from main branch

**Comment by saniales** [comment]
Yes, will do

**Comment by akhilerm** [comment]
@saniales Did you get a chance to test action from `@main`?

**Comment by saniales** [comment]
No but i will tomorrow

**Comment by saniales** [comment]
I tested it and it works, you can release new version

**Comment by akhilerm** [comment]
Thank you.

**Pull request merged**
